using System.Collections.Generic;

namespace Recipes.Models.ViewModels
{
    /// <summary>
    /// Carries the list of items generated by the Smart Grocery Generator,
    /// so that they can be posted back to a controller action.
    /// </summary>
    public class GeneratedGroceryItemViewModel
    {
        public List<GeneratedGroceryItem> Items { get; set; } = new List<GeneratedGroceryItem>();
    }

    /// <summary>
    /// Represents one grocery item (name, category, quantity, and nutrition)
    /// as returned by the generator.
    /// </summary>
    public class GeneratedGroceryItem
    {
        // Display name of the item (e.g., "Apple")
        public string Name { get; set; }

        // Category (e.g., "Fruit", "Vegetable", etc.)
        public string Category { get; set; }

        // Calculated quantity (e.g., 9)
        public int Quantity { get; set; }

        // Estimated calories per unit (e.g., 95)
        public int CaloriesPerUnit { get; set; }

        // Estimated protein per unit (e.g., 0 or 1)
        public int ProteinPerUnit { get; set; }
    }
}
